---
title: "EDA"
author: "Julie Tschanz"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate) #get informations on date
library(dplyr) #from tidyverse to tidy up the data
library(ggplot2) #For nicer plots
library(gridExtra) #To overlay the barplots
library(corrplot) #To do correlation heatmap
```
## Exploratory Data analysis

```{r}
data <- read.csv("df_agg_hourly.csv", header = TRUE)

data <- data %>%
  select(Datetime, VELO_IN, VELO_OUT, FUSS_IN, FUSS_OUT, Hr...Hr., RainDur..min., StrGlo..W.m2., T...C., WD...., Standort) #I selected only what I deemed important for the EDA

data$Datetime <- as.POSIXlt(data$Datetime)
#data$Year <- year(data$Datetime)
data$Month <- month(data$Datetime)
data$Day <- day(data$Datetime)
data$Hour <- hour(data$Datetime)
data$Datetime <- NULL

#Aggregation by hours only
data_hours <- data %>%
  group_by(Month, Day, Standort) %>%
  summarise(VELO_IN=sum(VELO_IN), VELO_OUT=sum(VELO_OUT), FUSS_IN=sum(FUSS_IN), FUSS_OUT=sum(FUSS_OUT), Hr...Hr.=mean(Hr...Hr., na.rm = TRUE), RainDur..min.=mean(RainDur..min., na.rm = TRUE), StrGlo..W.m2.=mean(StrGlo..W.m2., na.rm = TRUE), T...C.=mean(T...C., na.rm = TRUE), WD....=mean(WD...., na.rm = TRUE))

#Standort and hours aggregated
data_SO_hours <- data %>%
  group_by(Month, Day) %>%
  summarise(VELO_IN=sum(VELO_IN), VELO_OUT=sum(VELO_OUT), FUSS_IN=sum(FUSS_IN), FUSS_OUT=sum(FUSS_OUT), Hr...Hr.=mean(Hr...Hr., na.rm = TRUE), RainDur..min.=mean(RainDur..min., na.rm = TRUE), StrGlo..W.m2.=mean(StrGlo..W.m2., na.rm = TRUE), T...C.=mean(T...C., na.rm = TRUE), WD....=mean(WD...., na.rm = TRUE))


# Aggregated by month
data_month <- data %>%
  group_by(Month, Standort) %>%
  summarise(VELO_IN=sum(VELO_IN), VELO_OUT=sum(VELO_OUT), FUSS_IN=sum(FUSS_IN), FUSS_OUT=sum(FUSS_OUT), Hr...Hr.=mean(Hr...Hr., na.rm = TRUE), RainDur..min.=mean(RainDur..min., na.rm = TRUE), StrGlo..W.m2.=mean(StrGlo..W.m2., na.rm = TRUE), T...C.=mean(T...C., na.rm = TRUE), WD....=mean(WD...., na.rm = TRUE))

#Month and Standort aggregated
data_SO_month <- data %>%
  group_by(Month) %>%
  summarise(VELO_IN=sum(VELO_IN), VELO_OUT=sum(VELO_OUT), FUSS_IN=sum(FUSS_IN), FUSS_OUT=sum(FUSS_OUT), Hr...Hr.=mean(Hr...Hr., na.rm = TRUE), RainDur..min.=mean(RainDur..min., na.rm = TRUE), StrGlo..W.m2.=mean(StrGlo..W.m2., na.rm = TRUE), T...C.=mean(T...C., na.rm = TRUE), WD....=mean(WD...., na.rm = TRUE))
```

```{r}
custom <- c("Jan.", "Feb.", "Mar.", "Apr.", "May", "Jun.", "Jul.","Aug.", "Sep.", "Oct.", "Nov.", "Dec.")

#Barplot for the velo in during 2023
bar_plot_velo_in <- ggplot(data = data_SO_month, aes(x= Month, y=VELO_IN))+
  geom_bar(stat="identity", fill="lightblue", alpha = 0.7) +
  theme_minimal() +
  scale_x_discrete(limits=custom)

#barplot for the velo out during 2023
bar_plot_velo_out <- ggplot(data = data_SO_month, aes(x= Month, y=VELO_OUT))+
  geom_bar(stat="identity", fill="coral2", alpha = 0.7) +
  theme_minimal()+
  scale_x_discrete(limits=custom)



```


```{r}
#combined plot for both in and out velos
overlay_velo_plot <- ggplot(data_SO_month, aes(x=Month)) +
  geom_bar(aes(y = VELO_IN, fill = "IN"), stat = "identity", alpha = 0.7, position = "dodge") +
  geom_bar(aes(y = VELO_OUT, fill = "OUT"), stat = "identity", alpha = 0.7, position = "dodge") +
  scale_y_continuous(
    name = "VELO")+
  labs(title = "Velo in and out in 2023", x = "Month", fill = "Group") +
  scale_fill_manual(name = "Group", values = c("IN" = "skyblue", "OUT" = "coral")) +
  scale_x_discrete(limits=custom)+
  theme_minimal()


print(overlay_velo_plot)

```

```{r}
#Fuss data plotted by months for fuss in and out in 2023

overlay_fuss_plot <- ggplot() +
  geom_bar(data = data_SO_month, aes(x = Month, y = FUSS_IN, fill = "IN"), stat = "identity", alpha = 0.7, position = "dodge") +
  geom_bar(data = data_SO_month, aes(x = Month, y = FUSS_OUT, fill = "OUT"), stat = "identity", alpha = 0.7, position = "dodge") +
  labs(title = "Pedestrians in and out in 2023", x = "Month", y = "Pedestrians", fill = "Group") +
  scale_fill_manual(name = "Group", values = c("IN" = "lightgreen", "OUT" = "mediumpurple1")) +
  scale_x_discrete(limits=custom)+
  theme_minimal()


print(overlay_fuss_plot)

```




```{r}
#Heatmap maybe with what ??
# -> velo + fussand temperature + rain ?
data_SO_month_merged_column <- data_SO_month %>%
  mutate(VELO = VELO_IN+VELO_OUT, FUSS = FUSS_IN+FUSS_OUT)
cor_data_frame_SO_month <- data_SO_month_merged_column %>%
  select(Month, VELO, FUSS,RainDur..min., T...C. )

cor_matrix_SO_month <- cor(cor_data_frame_SO_month)

corrplot(cor_matrix_SO_month, method = "color", type = "upper", 
         tl.col = "black", tl.srt = 45,
         addrect = 2)
```

```{r}
#Table of summaries for the average velo and fuss traffic alongside the average rain and temperature, maybe per month or just over the year...

cor_data_frame_SO_month
```


```{r}
#Plot of January to show the seasonality due to the days of the week

#days_of_week <- c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat","Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Mon", "Tue", "Wed")
data_SO_hours_merged_column <- data_SO_hours %>%
  mutate(VELO = VELO_IN+VELO_OUT, FUSS = FUSS_IN+FUSS_OUT)

january <- data_SO_hours_merged_column %>%
  filter(Month %in% 1)

weekly_plot <- ggplot() +
  geom_bar(data = january, aes(x = Day, y = VELO), stat = "identity", alpha = 0.7, position = "dodge", fill="coral2") +
  labs(title = "Bycicles in January", x = "Days", y = "VELO", fill = "Group") +
  
  theme_minimal()

weekly_plot
```

```{r}
overlay_velo_plot <- ggplot(data_SO_month_merged_column, aes(x=Month)) +
  geom_bar(aes(y = VELO), stat = "identity", alpha = 0.7, position = "dodge", fill="skyblue") +
  scale_y_continuous(
    name = "VELO")+
  labs(title = "Total bicycles in 2023", x = "Month") +
  
  scale_x_discrete(limits=custom)+
  theme_minimal()


print(overlay_velo_plot)
```


```{r}
overlay_velo_plot <- ggplot(data_SO_month_merged_column, aes(x=Month)) +
  geom_bar(aes(y = FUSS), stat = "identity", alpha = 0.7, position = "dodge", fill="lightgreen") +
  scale_y_continuous(
    name = "FUSS")+
  labs(title = "Total pedestrians in 2023", x = "Month") +
  
  scale_x_discrete(limits=custom)+
  theme_minimal()


print(overlay_velo_plot)
```

```{r}
weekly_plot <- ggplot() +
  geom_bar(data = january, aes(x = Day, y = FUSS), stat = "identity", alpha = 0.7, position = "dodge", fill="coral2") +
  labs(title = "Pedestrians in January", x = "Days", y = "VELO", fill = "Group") +
  
  theme_minimal()

weekly_plot
```

